[package]
name = "embedded-graphics-rktk-test"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.19"
embedded-graphics = "0.8.1"
embedded-graphics-simulator = "0.7.0"
embedded-text = "0.7.2"
