[package]
name = "chromparint-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
rusty-chromaprint = "0.1.3"
symphonia = { version = "0.5.3", features = ["all-codecs", "all-formats"] }
